name: fuelet_uikit
description: A UIKit package for nft_app_flutter project
version: 1.0.7
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.0.0
  fl_chart: ^0.55.0
  intl: any
  just_the_tooltip: ^0.0.12
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: lib/fonts/Inter.ttf
