name: fuelet_uikit
description: A UIKit package for nft_app_flutter project
version: 1.0.16
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.0
  flutter_svg: ^1.1.6
  fl_chart: ^0.68.0
  intl: ^0.18.1
  just_the_tooltip: ^0.0.12
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: lib/fonts/Inter.ttf
        - asset: lib/fonts/Inter-Thin.ttf
          weight: 100
        - asset: lib/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: lib/fonts/Inter-Light.ttf
          weight: 300
        - asset: lib/fonts/Inter-Regular.ttf
          weight: 400
        - asset: lib/fonts/Inter-Medium.ttf
          weight: 500
        - asset: lib/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/Inter-Bold.ttf
          weight: 700
        - asset: lib/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: lib/fonts/Inter-Black.ttf
          weight: 900